books/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.home, name='home'),
    path('list/', views.book_list, name='book_list'),
    path('upload/', views.book_upload, name='book_upload'),
    path('library/', views.library, name='library'),
    path('download/<int:book_id>/', views.book_download, name='book_download'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

my_bookstore/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('books.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


print(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

books/models.py
from django.db import models
from django.contrib.auth.models import User


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    description = models.TextField()
    cover_image = models.ImageField(upload_to='book_covers/')
    book_file = models.FileField(upload_to='book_files/')


class Downloads(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    downloaded_at = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     unique_together = ('book', 'user')

   

books/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'description', 'cover_image', 'book_file')

books/views.py
from django.contrib import messages
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect , get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import BookForm
from django.contrib.auth.models import User
from .models import Book , Downloads
from django.contrib.auth import authenticate, login
from django.db.models import Q

def home(request):
    return render(request, 'base.html')

def book_list(request):
    search_query = request.GET.get('q', '')
    if search_query:
        books = Book.objects.filter(Q(title__icontains=search_query) | Q(author__icontains=search_query))
    else:
        books = Book.objects.all()
    return render(request, 'book_list.html', {'books': books, 'search_query': search_query})


def signup(request):
    if request.method == 'POST':
        uname = request.POST.get("username")
        email = request.POST.get("email")
        pass1 = request.POST.get("password")
        pass2 = request.POST.get("confirmPassword")
        if pass1 != pass2:
            return HttpResponse("Your PASSWORD and CONFIRM PASSWORD are not same")
        else:
            try:
                my_user = User.objects.create_user(uname,email,pass1)
                my_user.save()
                messages.success(request, 'You have successfully signed up!')
                return redirect('login')
            except IntegrityError:
                messages.error(request, 'Username already exists, please choose a different username')
    return render(request, 'signup.html')


def login(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('home')
        else:
            # Return an 'invalid login' error message.
            messages.error(request, 'Invalid username or password')
    return render(request, 'login.html')



@login_required
def book_upload(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = BookForm()
    return render(request, 'book_upload.html', {'form': form})


@login_required
def book_download(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    
    # Check if the user has already downloaded the book
    if Downloads.objects.filter(book=book, user=request.user).exists():
        messages.warning(request, 'You have already downloaded this book.')
    else:
        download = Downloads(book=book, user=request.user)
        download.save()
        messages.success(request, f'You have downloaded "{book.title}" successfully.')

    return render(request, 'book_download.html', {'book': book})



@login_required
def library(request):
    user_downloads = Downloads.objects.filter(user=request.user)
    user_books = [download.book for download in user_downloads]
    context = {
        'user_books': user_books,
    }
    return render(request, 'library.html', context)

books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Bookstore{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
          crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'book_list' %}">My Bookstore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" 
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'book_upload' %}">Upload Book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'library' %}">My Library</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0 ml-auto" method="get" action="{% url 'book_list' %}">
                <input class="form-control mr-sm-2" type="search" placeholder="Search for books" aria-label="Search" name="q" value="{{ search_query }}">
                <button class="btn btn-outline-white my-2 my-sm-0 bg-secondary" type="submit">Search</button>
            </form>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <span class="navbar-text">{{ user.username }}</span>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mt-3">
        {% block content %}
        {% endblock %}
    </div>
 <!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNVe1Xf" 
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
        integrity="sha384-JjSmVgyENG+nWwoD25GZ4qUZzOJ4Mhp6E9PPJjWYqjMBootstrap 4 exampleHnE003QwrD2Jd21qd" 
        crossorigin="anonymous"></script>


</body>
</html>

books/templates/book_download.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-4">
      <img src="{{ book.cover_image.url }}" alt="{{ book.title }} cover" class="img-fluid">
    </div>
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h1 class="card-title">{{ book.title }}</h1>
          <p class="card-subtitle">{{ book.author }}</p>
        </div>
        <div class="card-body">
          <p class="card-text">{{ book.description }}</p>
          <a href="{{ book.book_file.url }}" class="btn btn-primary btn-dark mt-1">Download</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

books/templates/book_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      {% for book in books %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{{ book.cover_image.url }}" alt="{{ book.title }} cover" style="max-height: 60vh ;min-height: 400px">
          <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <p class="card-text">{{ book.author }}</p>
            <a href="{% url 'book_download' book.id %}" class="btn btn-primary">Download</a>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-md-12">
        <p>No books have been uploaded yet.</p>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

books/templates/book_upload.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
  <h1>Upload a Book</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_title">Title:</label>
      <input type="text" id="id_title" name="title" class="form-control">
    </div>
    <div class="form-group">
      <label for="id_author">Author:</label>
      <input type="text" id="id_author" name="author" class="form-control">
    </div>
    <div class="form-group">
      <label for="id_description">Description:</label>
      <textarea id="id_description" name="description" class="form-control"></textarea>
    </div>
    <div class="form-group">
      <label for="id_cover_image">Cover Image:</label>
      <input type="file" id="id_cover_image" name="cover_image" class="form-control-file">
    </div>
    <div class="form-group">
      <label for="id_book_file">Book File:</label>
      <input type="file" id="id_book_file" name="book_file" class="form-control-file">
    </div>
    <button type="submit" class="btn btn-primary btn-dark">Upload</button>
  </form>
{% endblock %}

books/templates/library.html
{% extends 'base.html' %}

{% block content %}
  {% if user_books %}
    <div class="row">
      {% for book in user_books %}
         <div class="col-md-4 mb-4">
          <div class="card">
            <img src="{{ book.cover_image.url }}" alt="{{ book.title }} cover" style="max-height: 60vh; min-height: 400px">
            <div class="card-body">
              <h5 class="card-title">{{ book.title }}</h5>
              <p class="card-text">{{ book.author }}</p>
              {% comment %} <a href="{% url 'book_download' book.id %}" class="btn btn-primary">Download</a> {% endcomment %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p>No books downloaded yet.</p>
  {% endif %}
{% endblock %}

books/templates/login.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<div class="container d-flex justify-content-center">
  <form action="" method="post" class="w-50 my-5">
    {% csrf_token %}
    <input type="text" name="username" placeholder="USERNAME" class="form-control mb-3">
    <input type="password" name="password" placeholder="PASSWORD" class="form-control mb-3">
    <div class="text-center mt-3">
    <button type="submit" class="btn btn-primary btn-dark mt-3 px-5">Login</button>
    </div>
    <div class="text-center mt-4">
      <p>Don't have an account? <a href="{% url 'signup' %}">Sign up</a></p>
    </div>
  </form>
</div>
{% endblock %}

books/templates/logout.html
{% extends 'base.html' %}

{% block content %}
  <h1>Logout</h1>
  <p>You have been logged out.</p>
{% endblock %}

books/templates/signup.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<div class="container d-flex justify-content-center">
<form action="" method="post" class="w-50 my-5">
  {% csrf_token %}
  <input type="text" name="username" placeholder="USERNAME" class="form-control mb-3">
  <input type="email" name="email" placeholder="EMAIL" class="form-control mb-3">
  <input type="password" name="password" placeholder="PASSWORD" class="form-control mb-3">
  <input type="password" name="confirmPassword" placeholder="CONFIRM PASSWORD" class="form-control mb-3">
  <div class="text-center">
  <button type="submit" class="btn btn-primary btn-dark mb-3">Sign up</button>
  </div>
  <div class="text-center mt-4">
      <p>Already have an account? <a href="{% url 'login' %}">Log in</a></p>
  </div>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}

{% endblock %}